name: Tvbox-Yswag-sync
on:
  schedule:
    - cron: '20 2/12 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-Tvbox-Yswag-GithubSync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync Tvbox-Yswag-GithubSync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Yswag/uzVideo.git"
          source_branch: "main"
          destination_branch: "Tvbox-Yswag"
          github_token: ${{ secrets.PAT }}
